### ISSUE TITLE
Proposta de layouts

### ISSUE THREAD

**Issue by guilhermepontes** [valehackerspace/site#3]
Bora enviar umas propostas aqui neste tópico mesmo? (=
Assim que possível eu envio!

**Comment by guilhermepontes** [comment]
Aí galera, vejam se vocês conhecem alguém para apresentar algum template para o website.
Criei esse, deu um trabalho mas ainda falta muito pra terminar. 

Vejam aí se está legal.

![Proposta HackerSpaceVale](http://f.cl.ly/items/31342X3Q1m2U3w3d2E3T/HACKERSPACEVALE.jpg)

**Comment by zokis** [comment]
Cara por mim está aprovadíssimo!

**Comment by guilhermepontes** [comment]
Tem textos fakes roubados do garoa ai heuauhaeuhae e também foto de nao sei aonde... sei que é de um hackerspace tb.

**Comment by zokis** [comment]
Tem uma foto que o @giovaneliberato tirou ontem no ITA

**Comment by guilhermepontes** [comment]
Pra colocar aqui no avatar do github:
![Github HackerSpaceVale](http://f.cl.ly/items/0X3I1W3f1n2G2o460r38/hackerspace-github.jpg)

**Comment by giovaneliberato** [comment]
a que eu tirei no ITA ficou cagada, meu celular é zuado :s

mas ta aprovadíssimo o design

**Comment by guilhermepontes** [comment]
Galera, vou fazer uma segunda versão, eu não tinha percebido, tava no meu sub-conciente só pode, hahahah. 
Fiz praticamente igual o site da Gauge: http://www.gauge.com.br.

Hoje de noite eu faço de novo (=
Abs

**Comment by guilhermepontes** [comment]
A véio, vai ficar assim mesmo haeshioaeshoiase preguiça wins =(

**Comment by victorjtfranco** [comment]
Guilherme, ficou muito bom, eu só ia sugerir colocar o mapa e as informações abaixo em outra página ( para não demorar para carregar em conexões lentas, acho que vale a preocupação )

**Comment by guilhermepontes** [comment]
@victorjtfranco  no problem! (=

**Comment by guilhermepontes** [comment]
vamos ter que mudar tudo né. agora o nome é Sabugosa..

**Comment by zokis** [comment]
Provavelmente, juntou 4 iniciativas ai mudou o nome
tem que abrir uma discussão na lista
pra ver como vai ficar esse projeto de site, já tem um no ar provisório, enquanto isso não for discutido

**Comment by guilhermepontes** [comment]
vish...
